debug = false
path = "~/Pictures/art"
ca-file = "config/server/tls/root-ca.pem"
port = 6379
# pkcs8 private key
tls-key-file = "config/server/tls/server.key.pem"
# tls-cert-file is end-entity certificate
tls-cert-file = "config/server/tls/cert.pem"
# wait time of pageant mode in milliseconds
pageant-wait = 1000


